### ISSUE TITLE
AMI `/programs/NASC-seq/scripts/` old version

### ISSUE THREAD

**Issue by shayanhoss** [sandberg-lab/NASC-seq#3]
The folder for `/programs/NASC-seq/scripts/` in the AMI has the v2 of the `estimate_pi_g_STAN_forAWS_v3.py` so when executing the current version of the pipeline, the script can't find this program.

**Comment by gjhendriks** [comment]
I updated the version of the script. The new AMI should come online soon. I will then update the AMI ID in the description.

**Comment by gjhendriks** [comment]
The updated image is available in the OHIO region and is named NASC-seq (ami-09ed874a884ac41ed).

**Comment by shayanhoss** [comment]
@gjhendriks the image you stated is not available in the Public Images listings for Ohio. Nor is the original image.

**Comment by gjhendriks** [comment]
Sorry, the AMI was still private, is fixed now.

**Comment by shayanhoss** [comment]
Is it possible to change the permissions on the underlying snapshot for the AMI? I am trying to copy the AMI from Ohio to Oregon but am unable to because of the following error : 

 "You do not have permission to access the storage of this ami"

I was able to make a copy of the previous AMI to other regions.

**Comment by gjhendriks** [comment]
I have made the snapshot public as well.
