### ISSUE TITLE
Switch to conda/pip distribution of picard

### ISSUE THREAD

**Issue by shayanhoss** [sandberg-lab/NASC-seq#5]
I am using `conda env` to build the dependancies necessary for running the NASC-Seq pipeline. In your pipeline, picard is called using the `picard.jar` file is hardwired in, requiring the distribution of picard from their github. 

The distribution through [conda](https://anaconda.org/bioconda/picard) installs just fine and can be called directly. There is also a distribution through [pypi](https://pypi.org/project/picardtools/).

**Comment by gjhendriks** [comment]
Could you try the attached version of NASCseq_pipeline_pe_v2.py and let me know if it worked?

[NASCseq_pipeline_pe_v2_1.txt](https://github.com/sandberg-lab/NASC-seq/files/3718695/NASCseq_pipeline_pe_v2_1.txt)

**Comment by gjhendriks** [comment]
Did this work for you?
