### ISSUE TITLE
Can NASC-seq run the mouse data?

### ISSUE THREAD

**Issue by bitcometz** [sandberg-lab/NASC-seq#7]
Hello, I used mouse sample to do the SLAM-Seq.
Can I run NASC-seq to generate the outputs for the dynamo?

Best

**Comment by gjhendriks** [comment]
The NASC-seq analysis pipeline is fine to use for mouse data. However, it is intended for single-cell data and not for bulk SLAM-seq. The step where we filter SNPs is dependent on there being many samples (i.e. cells) and will therefore not work for bulk data with few samples.

**Comment by bitcometz** [comment]
Dear gjhendriks,
Thanks for your reply !!! 
Sorry, I didn't write it clearly before. My data was obtained by single-cell sequencing.
Thank you very much for pointing out what I need to pay attention to.
I have tested this process and it seems that there is no problem. 
Next, I will try to learn more about your pipeline and it is a great job.

Best
